# Generated by Django 4.0.1 on 2022-01-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('grade', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
